stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    outs:
    - data/raw
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/raw
    - src/model/model_building.py
    outs:
    - models/model.pkl
  model_eval:
    cmd: python src/model/model_eval.py
    deps:
    - models/model.pkl
    - src/model/model_eval.py
    metrics:
    - reports/metrics.json
